name: CI/CD Pipeline

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask scikit-learn joblib sentry-sdk autopep8 black pylint flake8

    - name: Lint and format with pylint and flake8
      run: |
        pylint app.py model.py || true
        flake8 app.py model.py || true

    - name: Auto fix code style issues
      run: |
        autopep8 --in-place --aggressive --aggressive app.py model.py
        black app.py model.py

    - name: Run tests
      run: |
        python -m unittest discover
